PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS businesses(id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL REFERENCES businesses(id), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS business_settings(business_id INTEGER PRIMARY KEY REFERENCES businesses(id), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL REFERENCES businesses(id), name TEXT NOT NULL, data TEXT NOT NULL, archived INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY, business_id INTEGER REFERENCES businesses(id), name TEXT NOT NULL, UNIQUE(business_id,name));
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL REFERENCES businesses(id), category_id INTEGER REFERENCES categories(id), name TEXT NOT NULL, sku TEXT NOT NULL, data TEXT NOT NULL, selling_price INTEGER NOT NULL CHECK(selling_price>=0), purchase_price INTEGER NOT NULL CHECK(purchase_price>=0), mrp INTEGER NOT NULL CHECK(mrp>=0), active INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(business_id,sku));
CREATE TABLE IF NOT EXISTS inventory(product_id INTEGER PRIMARY KEY REFERENCES products(id), quantity INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL REFERENCES businesses(id), customer_id INTEGER NOT NULL REFERENCES customers(id), number TEXT NOT NULL, date TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('GST','NON-GST')), status TEXT NOT NULL DEFAULT 'FINAL', subtotal INTEGER NOT NULL, discount INTEGER NOT NULL, taxable INTEGER NOT NULL, cgst INTEGER NOT NULL, sgst INTEGER NOT NULL, igst INTEGER NOT NULL, total INTEGER NOT NULL, snapshot TEXT NOT NULL, version INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(business_id,number));
CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES invoices(id), product_id INTEGER REFERENCES products(id), name TEXT NOT NULL, quantity INTEGER NOT NULL, rate INTEGER NOT NULL, mrp INTEGER NOT NULL, gst TEXT NOT NULL, hsn TEXT NOT NULL, discount INTEGER NOT NULL, taxable INTEGER NOT NULL, tax INTEGER NOT NULL, total INTEGER NOT NULL, unit TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES invoices(id), amount INTEGER NOT NULL CHECK(amount>0), date TEXT NOT NULL, method TEXT NOT NULL, reference TEXT NOT NULL, notes TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id), invoice_id INTEGER REFERENCES invoices(id), quantity INTEGER NOT NULL, reason TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY, business_id INTEGER REFERENCES businesses(id), user_id INTEGER REFERENCES users(id), action TEXT NOT NULL, entity TEXT NOT NULL, entity_id INTEGER, details TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS login_attempts(key TEXT PRIMARY KEY, count INTEGER NOT NULL, started INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS invoice_submissions(business_id INTEGER NOT NULL REFERENCES businesses(id), token TEXT NOT NULL, invoice_id INTEGER NOT NULL REFERENCES invoices(id), PRIMARY KEY(business_id,token));
CREATE INDEX IF NOT EXISTS invoices_business_date ON invoices(business_id,date);
CREATE INDEX IF NOT EXISTS customers_business ON customers(business_id,archived);
CREATE INDEX IF NOT EXISTS products_business ON products(business_id,active);
CREATE INDEX IF NOT EXISTS payments_invoice ON payments(invoice_id,date);
CREATE INDEX IF NOT EXISTS stock_product ON stock_movements(product_id,created_at);
